config:
  whatsapp:
    number: 31600000000 #number
    password: '' #password
  slack:
    key: '' #slack bot key

channels:
  key: #just a random name or so, repeat this for every channel it's active in
    whatsapp: '' #id of the whatsapp group/chat
    slack: '' #id of the slack channel

contacts:
  key: #just a random key or so, could maybe be the name, repeat for every contact
    name: '' #name of the person
    whatsapp: 31600000000 #number
    slack: '' #slack id